import React, { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Lock, ArrowLeft } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { updatePasswordThunk, checkSession, selectIsAuthenticated } from '../store/slices/authSlice';
import { Input } from '../components/ui/Input';
import { toast } from 'react-toastify';

const resetPasswordSchema = z.object({
  password: z.string().min(8, 'Password must be at least 8 characters'),
  confirmPassword: z.string().min(8, 'Please confirm your password')
}).refine((data) => data.password === data.confirmPassword, {
  message: "Passwords don't match",
  path: ["confirmPassword"],
});

export default function ResetPassword() {
  const [loading, setLoading] = useState(false);
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const isAuthenticated = useSelector(selectIsAuthenticated);

  useEffect(() => {
    // Attempt to verify session generated by the email recovery link
    dispatch(checkSession());
  }, [dispatch]);

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(resetPasswordSchema),
    defaultValues: { password: '', confirmPassword: '' }
  });

  const passwordValue = watch('password');
  const confirmPasswordValue = watch('confirmPassword');
  const isDisabled = !passwordValue || !confirmPasswordValue || loading;

  const onSubmit = async (data) => {
    if (!isAuthenticated) {
      toast.error('Invalid or expired reset session. Please request a new link.');
      return;
    }

    setLoading(true);
    try {
      await dispatch(updatePasswordThunk(data.password)).unwrap();
      toast.success('Password updated successfully');
      navigate('/auth');
    } catch (error) {
      toast.error(error || 'Failed to update password');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-background-dark text-slate-100 min-h-screen flex flex-col items-center justify-start font-body antialiased relative">
      <div className="w-full max-w-[430px] min-h-screen flex flex-col px-8 py-12 relative overflow-hidden z-10">
        
        {/* Header */}
        <div className="flex items-center mb-8">
          <Link to="/auth" className="p-2 -ml-2 rounded-full hover:bg-white/5 transition-colors">
            <ArrowLeft className="text-white w-6 h-6" />
          </Link>
        </div>

        {/* Title */}
        <div className="flex flex-col mb-10">
          <div className="w-16 h-16 bg-primary/10 rounded-2xl flex items-center justify-center mb-6 ring-1 ring-primary/20">
            <Lock className="text-primary w-8 h-8" strokeWidth={1.5} />
          </div>
          <h1 className="text-3xl font-bold tracking-tight text-white mb-2">Reset Password</h1>
          <p className="text-slate-400 text-sm leading-relaxed">
            Create a new strong password for your account.
          </p>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6 flex-1">
          <Input
            label="New Password"
            icon={Lock}
            type="password"
            placeholder="••••••••"
            error={errors.password?.message}
            {...register('password')}
          />
          <Input
            label="Confirm Password"
            icon={Lock}
            type="password"
            placeholder="••••••••"
            error={errors.confirmPassword?.message}
            {...register('confirmPassword')}
          />
          <button
            type="submit"
            disabled={isDisabled}
            className="w-full bg-primary hover:bg-[#00d1b8] text-background-dark font-bold py-4 rounded-lg shadow-lg shadow-primary/10 transition-all active:scale-[0.98] mt-8 disabled:opacity-50 disabled:active:scale-100 disabled:cursor-not-allowed flex justify-center items-center"
          >
            {loading ? (
              <div className="w-5 h-5 border-2 border-background-dark border-t-transparent rounded-full animate-spin"></div>
            ) : (
              'Reset Password'
            )}
          </button>
        </form>

        {/* Decorative elements */}
        <div className="fixed top-[-10%] left-[-20%] w-[70%] h-[70%] bg-primary/10 blur-[130px] rounded-full pointer-events-none opacity-40 z-[-1]"></div>
      </div>
    </div>
  );
}
